services:

  database:
    image: postgres:15
    container_name: nestjs_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    container_name: node-app
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
